config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks',
                                    sessions: 'users/sessions',
                                    registrations: 'users/registrations'}
  devise_scope :user do
    get     "/signup",  to: "users/registrations#new"
    get     "/login",   to: "users/sessions#new"
    post    "/login",   to: "users/sessions#create"
    delete  "/logout",   to:"users/sessions#destroy"
  end

  root "static_pages#home"
  get "/help",          to: "static_pages#help"
  get "/about",         to: "static_pages#about"
  get "/contact",       to: "static_pages#contact"
  get "/plivacypolicy", to: "static_pages#plivacypolicy"

  delete "/notifications/destroy", to: "notifications#destroy_all"

  resources :users,                  only: [:show] do
    member do
      get :following, :followers
    end
  end

  resources :microposts,              only: [:new,:show,:create,:destroy] do
    resources :comments,              only: [:create,:destroy]
  end

  resources :relationships,           only: [:create,:destroy]

  resources :notifications,           only: :index

  resources :favorite_relationships,  only: [:create, :destroy]

  resources :searchs,                 only: :index

  resources :password_edits,          only: [:edit,:update]

end

app/models/notification.rb
class Notification < ApplicationRecord

  default_scope->{order(created_at: :desc)}

  belongs_to :micropost,  optional: true
  belongs_to :comment,    optional: true
  belongs_to :visiter,    class_name: 'User',
                          foreign_key: 'visiter_id',
                          optional: true
  belongs_to :visited,    class_name: 'User',
                          foreign_key: 'visited_id',
                          optional: true

end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  before_action :authenticate_user!

  def index
      @notifications = current_user.passive_notifications
      @notifications.where(checked: false).each do |notification|
          notification.update_attributes(checked: true)
      end
  end

  def destroy_all
      @notifications = current_user.passive_notifications.destroy_all
      redirect_to notifications_path
  end
  
end

app/helpers/notifications_helper.rb
module NotificationsHelper

  def notification_form(notification)
      @visiter = notification.visiter
      @comment = nil
      your_item = link_to 'あなたの投稿', micropost_path(notification), style:"font-weight: bold;"
      @visiter_comment = notification.comment_id
      #notification.actionがfollowかlikeかcommentか
      case notification.action
        when "follow" then
          tag.a(notification.visiter.name, href: user_path(@visiter), style:"font-weight: bold;")+"があなたをフォローしました"
        when "like" then
          tag.a(notification.visiter.name, href: user_path(@visiter), style:"font-weight: bold;")+"が"+tag.a('あなたの投稿', href: micropost_path(notification.micropost_id), style:"font-weight: bold;")+"にいいねしました"
        when "comment" then
            @comment = Comment.find_by(id: @visiter_comment)&.content
            tag.a(@visiter.name, href:user_path(@visiter), style:"font-weight: bold;")+"が"+tag.a('あなたの投稿', href: micropost_path(notification.micropost_id), style:"font-weight: bold;")+"にコメントしました"
      end
    end

    def unchecked_notifications
      @notifications = current_user.passive_notifications.where(checked: false)
    end
end

app/views/notifications/_notification.html.erb
<% visiter = notification.visiter %>
<% micropost = notification.micropost %>
<div class="user-view clearfix ">
  <%= link_to user_path(notification.visiter) do %>
    <%= image_tag visiter.image %>
  <% end %>
  <%= notification_form(notification) %><span class="moderate-font"><%= " (#{time_ago_in_words(notification.created_at)}前)" %></span>
  <br>
  <% if !@comment.nil? %>
    <p class="moderate-font text-center" style="color: #C0C0C0;"><%= @comment %></p>
  <% end %>
</div>

app/views/notifications/index.html.erb
<div class="notification-page">
  <% provide(:title,"通知") %>
  <%= link_to notifications_destroy_path,method: :delete do %>
      <i class="fas fa-trash" style="color: black;"></i>
      <h7 style="color: black;">全削除</h7>
  <% end %>
      <hr>
  <% if @notifications.exists? %>
      <div class="users-index">
          <%= render @notifications %>
      </div>
  <% else %>
      <p>通知はありません</p>
  <% end %>
</div>