config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks',
                                    sessions: 'users/sessions',
                                    registrations: 'users/registrations'}
  devise_scope :user do
    get     "/signup",  to: "users/registrations#new"
    get     "/login",   to: "users/sessions#new"
    post    "/login",   to: "users/sessions#create"
    delete  "/logout",   to:"users/sessions#destroy"
  end

  root "static_pages#home"
  get "/help",          to: "static_pages#help"
  get "/about",         to: "static_pages#about"
  get "/contact",       to: "static_pages#contact"
  get "/plivacypolicy", to: "static_pages#plivacypolicy"

  delete "/notifications/destroy", to: "notifications#destroy_all"

  resources :users,                  only: [:show] do
    member do
      get :following, :followers
    end
  end

  resources :microposts,              only: [:new,:show,:create,:destroy] do
    resources :comments,              only: [:create,:destroy]
  end

  resources :relationships,           only: [:create,:destroy]

  resources :notifications,           only: :index

  resources :favorite_relationships,  only: [:create, :destroy]

  resources :searchs,                 only: :index

  resources :password_edits,          only: [:edit,:update]

end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="microposts">
    <%= render @feed_items %>
  </ol>
  <%= will_paginate @feed_items,params:{contorller: :static_pages,action: :home } %>
<% end %>

app/views/shared/_micropost_menu.html.erb
<div class="micropost-menu">
  <span class="like" id="like_form_<%= micropost.id %>">
    <% if micropost.liked_by.include?(current_user) %>
      <%= render "microposts/unlike", micropost: micropost %>
    <% else %>
      <%= render "microposts/like", micropost: micropost %>
    <% end %>
  </span>
  <span class="comment-form">
    <%= form_with(model: [micropost,@comment], local: true)do |f| %>
      <span class="comment-content">
        <%= f.text_field :content %>
      </span>
      <%= f.submit "コメントする", class: "btn btn-primary" %>
    <% end %>
  </span>
  <% if current_user == micropost.user  %>
    <%= link_to "削除", micropost, method: :delete,
                                     data: { confirm: "本当によろしいですか?" },class: "comment-delete-btn btn btn-danger" %>
  <% end %>
</div>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
      <%= @user.following.count %>
    </strong>
    フォロー
  </a>
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    フォロワー
  </a>
</div>

app/views/shared/_user_info.html.erb
<%= link_to image_tag(current_user.image,class: "my_icon"), current_user %>
<h1><%= current_user.nickname %></h1>
<span><%= link_to "マイページ", current_user %></span>
<span><b>投稿:</b> <%= current_user.microposts.count %>件</span>